Adding second backend server to ci.yml and also changed homeController

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,19 +32,19 @@ jobs:
           name: employee-management-app  
           path: target/*.jar
 
-      - name: copy artifact to server
+      - name: copy artifact to server 1
         uses: appleboy/scp-action@v0.1.3
         with:
-          host: ${{ secrets.EC2_BACKEND_HOST }}
+          host: ${{ secrets.BACKEND_1_HOST }}
           username: ${{ secrets.EC2_BACKEND_USER }}
           key: ${{ secrets.EC2_BACKEND_KEY }}
           source: "target/*.jar"
           target: "/tmp"
 
-      - name: Moving Jar to Release Directory
+      - name: Moving Jar to Release Directory on Server 1
         uses: appleboy/ssh-action@v1
         with: 
-          host: ${{ secrets.EC2_BACKEND_HOST }}
+          host: ${{ secrets.BACKEND_1_HOST }}
           username: ${{ secrets.EC2_BACKEND_USER }}
           key: ${{ secrets.EC2_BACKEND_KEY }}
           script: |
@@ -63,10 +63,10 @@ jobs:
             sudo chown appuser:appuser /opt/employee-app/releases/$Release_name
             echo "Jar file moved successfully."
 
-      - name: Verifying Deployment
+      - name: Verifying Deployment on Server 1
         uses: appleboy/ssh-action@v1
         with: 
-          host: ${{ secrets.EC2_BACKEND_HOST }}
+          host: ${{ secrets.BACKEND_1_HOST }}
           username: ${{ secrets.EC2_BACKEND_USER }}
           key: ${{ secrets.EC2_BACKEND_KEY }}
           script: |
@@ -74,10 +74,10 @@ jobs:
             echo "Listing the contents of /opt/employee-app/releases directory:"
             sudo -u appuser ls -l /opt/employee-app/releases
 
-      - name: Restarting Application Service
+      - name: Restarting Application Service on Server 1
         uses: appleboy/ssh-action@v1
         with: 
-          host: ${{ secrets.EC2_BACKEND_HOST }}
+          host: ${{ secrets.BACKEND_1_HOST }}
           username: ${{ secrets.EC2_BACKEND_USER }}
           key: ${{ secrets.EC2_BACKEND_KEY }}
           script: |
@@ -112,10 +112,10 @@ jobs:
             echo "==============================================="
             echo "✅ Application service restarted successfully."
             echo "==============================================="
-      - name: cleanup old releases
+      - name: cleanup old releases on Server 1
         uses: appleboy/ssh-action@v1
         with: 
-          host: ${{ secrets.EC2_BACKEND_HOST }}
+          host: ${{ secrets.BACKEND_1_HOST }}
           username: ${{ secrets.EC2_BACKEND_USER }}
           key: ${{ secrets.EC2_BACKEND_KEY }}
           script: |
@@ -135,3 +135,108 @@ jobs:
                echo "Cleanup not required."
             fi
 
+      - name: copy artifact to server 2
+        uses: appleboy/scp-action@v0.1.3
+        with:
+          host: ${{ secrets.BACKEND_2_HOST }}
+          username: ${{ secrets.EC2_BACKEND_USER }}
+          key: ${{ secrets.EC2_BACKEND_KEY }}
+          source: "target/*.jar"
+          target: "/tmp"
+
+      - name: Moving Jar to Release Directory on Server 2
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.BACKEND_2_HOST }}
+          username: ${{ secrets.EC2_BACKEND_USER }}
+          key: ${{ secrets.EC2_BACKEND_KEY }}
+          script: |
+            echo "Checking Jar file path in /tmp directory..."
+            JAR_FILE=$(find /tmp -name "*.jar" | head -n 1)
+            if [ -z "$JAR_FILE" ]; then
+             echo "ERROR: No JAR file found on /tmp!"
+             exit 1
+            fi
+            echo "Found JAR file: $JAR_FILE on the server. Moving to /opt/employee-app/releases directory..."
+            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
+            Release_name="employee-management-${TIMESTAMP}.jar"
+            sudo mkdir -p /opt/employee-app/releases
+            sudo mv "$JAR_FILE" /opt/employee-app/releases/$Release_name 
+            sudo ln -sfn /opt/employee-app/releases/$Release_name /opt/employee-app/current.jar
+            sudo chown appuser:appuser /opt/employee-app/releases/$Release_name
+            echo "Jar file moved successfully."
+  
+      - name: Verifying Deployment on Server 2
+        uses: appleboy/ssh-action@v1
+        with: 
+          host: ${{ secrets.BACKEND_2_HOST }}
+          username: ${{ secrets.EC2_BACKEND_USER }}
+          key: ${{ secrets.EC2_BACKEND_KEY }}
+          script: |
+            echo "Deployment successful. Verifying the JAR..."
+            echo "Listing the contents of /opt/employee-app/releases directory:"
+            sudo -u appuser ls -l /opt/employee-app/releases
+            
+            
+      - name: Restarting Application Service on Server 2
+        uses: appleboy/ssh-action@v1
+        with: 
+          host: ${{ secrets.BACKEND_2_HOST }}
+          username: ${{ secrets.EC2_BACKEND_USER }}
+          key: ${{ secrets.EC2_BACKEND_KEY }}
+          script: |
+            set -e
+            echo "----------------------------------------"
+            echo "Restarting the application service..."
+            echo "----------------------------------------"
+            set +e
+            sudo systemctl restart employee_app
+            status=$?
+            set -e
+            if [ $status -ne 0 ]; then
+              echo "ERROR: ❌Failed to restart the application service. Please check the service logs for more details."
+              exit 1
+            fi
+            echo "Waiting for application to become healthy..."
+            for i in {1..6}; do
+              if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
+                echo "✅ Application is healthy."
+                break
+              fi
+              echo "Attempt $i/6 - Application not ready. Waiting..."
+              sleep 5
+            done
+            if ! curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
+              echo "ERROR: ❌ Application is not healthy. Please check the service logs for more details."
+              echo "Last 30 lines of application logs:"
+              sudo journalctl -u employee_app --no-pager --lines=30
+              exit 1
+            fi
+            sudo systemctl status employee_app --no-pager --lines=20
+            echo "==============================================="
+            echo "✅ Application service restarted successfully."
+            echo "==============================================="
+
+      - name: cleanup old releases on Server 2
+        uses: appleboy/ssh-action@v1
+        with: 
+          host: ${{ secrets.BACKEND_2_HOST }}
+          username: ${{ secrets.EC2_BACKEND_USER }}
+          key: ${{ secrets.EC2_BACKEND_KEY }}
+          script: |
+            echo "Checking total jar count in your release Directory and cleaning up old releases if necessary..."
+            RELEASE_DIR="/opt/employee-app/releases"
+            RELEASE_COUNT=$(ls "$RELEASE_DIR"/*.jar 2>/dev/null | wc -l)
+            echo "Total Jar Count: $RELEASE_COUNT"
+            if [ "$RELEASE_COUNT" -gt 5 ]; then
+               echo "More than 5 jars found. Cleaning up old releases..."
+               echo "Deleting the following releases:"
+               ls "$RELEASE_DIR"/*.jar | sort | head -n -5
+               ls "$RELEASE_DIR"/*.jar | sort | head -n -5 | xargs sudo rm | xargs sudo rm 
+               echo "Cleanup completed."
+               echo "Remaining releases:"
+               ls -1 "$RELEASE_DIR"/*.jar
+            else
+               echo "Cleanup not required."
+            fi        
+          
